### ISSUE TITLE
Use --local to tell shards to not refresh the cache

### ISSUE THREAD

**Issue by ysbaddaden** [GrantBirki/crystal-base-template#1]
The following line should be `shards install --local --frozen`:

https://github.com/GrantBirki/crystal-base-template/blob/5a318ffeb905366e18b92d95be985b6f3189a6a4/script/bootstrap#L68

That should tell shards to not refresh the cache (that you vendored) and assuming the cache is yup to date with `shard.lock`, then the install command shall complete normally without hitting the network. Since you vendor the cache folder, you likely don't need the `lib` folder either.

**Comment by GrantBirki** [comment]
@ysbaddaden Thanks for the help here! So I added `--local` to my bootstrap script. I am now able to run `script/bootstrap` locally without it making any requests for shards over the network. However, in GitHub Actions (my build system), it is failing

Locally:

![Image](https://github.com/GrantBirki/crystal-base-template/assets/23362539/7c74b024-2ae6-4560-aff9-606194806e5d)

GitHub Actions:

![Image](https://github.com/GrantBirki/crystal-base-template/assets/23362539/9915ee10-f4f7-4fd5-bdb9-6b65ecdf9117)

Perhaps I need to commit my `.cache/shards/` directory as seen in my "locally" screenshot?

---

FYI here is the pull request https://github.com/GrantBirki/crystal-base-template/pull/2 that I am working on to try and get this working

**Comment by GrantBirki** [comment]
I just made a video as well and posted it to the original thread looking for help -> https://github.com/crystal-lang/shards/issues/611#issuecomment-2073535127

**Comment by GrantBirki** [comment]
I've done it and its now on `main`! 🎉
